language: node_js
node_js:
- "0.10"
branches:
  only:
    - master
script:
  "gulp build:prod"
after_success:
  "gulp deploy"
cache:
  directories:
  - node_modules
env:
  global:
    - SITE_URL="http://eddywashere.com"
    - DISQUS="eddywashere"
    - GOOGLE_ANALYTICS="UA-7686535-1"